package school_management;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author asgha
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login_page
     */
    Connection Sqlconnection = Connect.ConnectDB();
    PreparedStatement prepared_statement = null;
    ResultSet rs = null;

    public login_page() {
        initComponents();
        displayfirst();
    }

    private void displayfirst() {

        idlbl.setVisible(false);
        emaillbl.setVisible(false);
        idtxt.setVisible(false);
        emailtxt.setVisible(false);
        signupbtn.setVisible(true);
    }

    private void uservarification() {

        String username = unametxt.getText();
        String password = passwdtxt.getText();

        try {
            if (forcombo.getSelectedItem().toString().equalsIgnoreCase("Adminstrator")) {
                prepared_statement = Sqlconnection.prepareStatement("select * from signup_admin where username=? and password=?");
                prepared_statement.setString(1, username);
                prepared_statement.setString(2, password);
                rs = prepared_statement.executeQuery();
                if (rs.next()) {
                    home_pageAdmin home = new home_pageAdmin();
                    home.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "wrong user name or Password");
                }

            }
            if (forcombo.getSelectedItem().toString().equalsIgnoreCase("Student")) {
                prepared_statement = Sqlconnection.prepareStatement("select * from add_student where username=? and idroll=? and email=?");
                String ids = idtxt.getText();
                String em = emailtxt.getText();
                prepared_statement.setString(1, username);
                prepared_statement.setString(2, ids);
                prepared_statement.setString(3, em);

                rs = prepared_statement.executeQuery();
                if (rs.next()) {
//                    student_page sp = new student_page(ids);
//                    sp.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "wrong user name or Password or Id email");
                }
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT mod ify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        uname = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        passwdlbl = new javax.swing.JLabel();
        passwdtxt = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        signupbtn = new javax.swing.JButton();
        forcombo = new javax.swing.JComboBox<>();
        fname = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        idlbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/admin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 63));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 140, 65));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 100));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setForeground(new java.awt.Color(255, 0, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText("User Name:");
        jPanel3.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 130, 30));

        unametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unametxtActionPerformed(evt);
            }
        });
        jPanel3.add(unametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 230, 30));

        passwdlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwdlbl.setForeground(new java.awt.Color(255, 255, 255));
        passwdlbl.setText("Password :");
        jPanel3.add(passwdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 30));

        passwdtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdtxtActionPerformed(evt);
            }
        });
        passwdtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwdtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwdtxtKeyReleased(evt);
            }
        });
        jPanel3.add(passwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 230, 30));

        loginbtn.setBackground(new java.awt.Color(0, 51, 102));
        loginbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/login.png"))); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel3.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        exitbtn.setBackground(new java.awt.Color(0, 51, 102));
        exitbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/exit.png"))); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel3.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, 33));

        signupbtn.setBackground(new java.awt.Color(0, 51, 102));
        signupbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signupbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/signup.png"))); // NOI18N
        signupbtn.setText("Signup");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel3.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 33));

        forcombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adminstrator", "Student" }));
        forcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forcomboActionPerformed(evt);
            }
        });
        jPanel3.add(forcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 230, 40));

        fname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setText(" For :");
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 30));

        idtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        jPanel3.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 230, 30));

        emailtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel3.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 230, 30));

        idlbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        idlbl.setForeground(new java.awt.Color(255, 255, 255));
        idlbl.setText("ID:");
        jPanel3.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 40, 30));

        emaillbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        emaillbl.setText("Email:");
        jPanel3.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 30));

        backButton.setBackground(new java.awt.Color(0, 51, 102));
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel3.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 550, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 450));

        setSize(new java.awt.Dimension(568, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unametxtActionPerformed

    private void passwdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwdtxtActionPerformed

    private void passwdtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwdtxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwdtxtKeyPressed

    private void passwdtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwdtxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwdtxtKeyReleased

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        signup_page signup = new signup_page();
        signup.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signupbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        uservarification();
    }//GEN-LAST:event_loginbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void forcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forcomboActionPerformed
        // TODO add your handling code here:
        if (forcombo.getSelectedItem().toString().equalsIgnoreCase("Adminstrator")) {
            idlbl.setVisible(false);
            emaillbl.setVisible(false);
            idtxt.setVisible(false);
            emailtxt.setVisible(false);
            passwdlbl.setVisible(true);
            passwdtxt.setVisible(true);

            signupbtn.setVisible(true);

        }
        if (forcombo.getSelectedItem().toString().equalsIgnoreCase("Student")) {
            idlbl.setVisible(true);
            emaillbl.setVisible(true);
            idtxt.setVisible(true);
            emailtxt.setVisible(true);
            signupbtn.setVisible(false);
            passwdlbl.setVisible(false);
            passwdtxt.setVisible(false);

        }


    }//GEN-LAST:event_forcomboActionPerformed

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainMenu2 menu = new MainMenu2();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login_page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel fname;
    private javax.swing.JComboBox<String> forcombo;
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel passwdlbl;
    private javax.swing.JPasswordField passwdtxt;
    private javax.swing.JButton signupbtn;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField unametxt;
    // End of variables declaration//GEN-END:variables
}
