package school_management;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class printReciept_page extends javax.swing.JFrame {

    java.sql.Connection Sqlconnection = Connect.ConnectDB();
    PreparedStatement prepared_statement = null;
    ResultSet result_set = null;

    /**
     * Creates new form printReciept_page
     */
    public printReciept_page() {
        initComponents();
        getrecord();

    }

    private void getrecord() {
        try {
            prepared_statement = Sqlconnection.prepareStatement("select * from fees_data order by id desc limit 1");
            result_set = prepared_statement.executeQuery();
            result_set.next();

            reciptxt.setText(result_set.getString("recieptno"));
            amounttxt.setText(result_set.getString("amount"));
            cgsttxt.setText(result_set.getString("cgst"));
            sgsttxt1.setText(result_set.getString("sgst"));
            recivedtxt.setText(result_set.getString("studentname"));

//            coursenmetxr.setText(result_set.getString("recieptno"));
            datetxt.setText(result_set.getString("date"));
            gsintxt.setText(result_set.getString("gstin"));
            totalamounttxt.setText(result_set.getString("totalamount"));
            year1txt.setText(result_set.getString("year1"));
            year2txt.setText(result_set.getString("year2"));
            remarkstxt.setText(result_set.getString("remarks"));
            totalinwordstxt.setText(result_set.getString("total_inwords"));
            paymentmodetxt.setText(result_set.getString("paymentm"));

            String pymode = result_set.getString("paymentm");
//                        paymentmodetxt.setText(result_set.getString("paymentm"));
            if (pymode.equalsIgnoreCase("Cheque")) {
                chequtxt.setText(result_set.getString("chequno"));
                banktxt.setText(result_set.getString("bankname"));
                chequelbl.setText("Cheque No:");

            }
            if (pymode.equalsIgnoreCase("DD")) {
                chequtxt.setText(result_set.getString("ddno"));
                banktxt.setText(result_set.getString("bankname"));
                chequelbl.setText("DD No:");
//                            dnotxt.setText(result_set.getString("ddno"));

            }
            if (pymode.equalsIgnoreCase("card")) {
//                            chequtxt.setText(result_set.getString("ddno"));
                banktxt.setText(result_set.getString("bankname"));
//                           chequelbl.setText(result_set.getString("DD No:")); 
//                            dnotxt.setText(result_set.getString("ddno"));

            }

//            reciptxt.setText(result_set.getString("recieptno"));
//            JOptionPane.showMessageDialog(null, "asdhfkhasdi");
        } catch (HeadlessException | SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        printpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chequelbl = new javax.swing.JLabel();
        recivedtxt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gsintxt = new javax.swing.JLabel();
        reciptxt = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        datetxt = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        banktxt = new javax.swing.JLabel();
        year1txt = new javax.swing.JLabel();
        year2txt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        totalinwordstxt = new javax.swing.JLabel();
        totalamounttxt = new javax.swing.JLabel();
        sgsttt = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        remarkstxt = new javax.swing.JLabel();
        amounttxt = new javax.swing.JLabel();
        cgsttxt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        chequtxt = new javax.swing.JLabel();
        banklbl1 = new javax.swing.JLabel();
        banklbl2 = new javax.swing.JLabel();
        paymentmodetxt = new javax.swing.JLabel();
        cgsttt1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        sgsttxt1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cgsttt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/printer-.png"))); // NOI18N
        jLabel1.setText(" Print");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelsidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 330, 70));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/edit2.png"))); // NOI18N
        jLabel11.setText(" Edit Reciept");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 70));

        panelsidebar.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 330, 70));

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/left-arrow.png"))); // NOI18N
        jLabel19.setText("  Back");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 310, 60));

        panelsidebar.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 330, 70));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/view all record.png"))); // NOI18N
        jLabel10.setText(" View All Records");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 70));

        panelsidebar.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, 70));

        jPanel16.setBackground(new java.awt.Color(0, 102, 102));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/list_1.png"))); // NOI18N
        jLabel21.setText("  Course List");
        jPanel16.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsidebar.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 330, 70));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/edit2.png"))); // NOI18N
        jLabel23.setText("  Edit Courses");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsidebar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 330, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/home.png"))); // NOI18N
        jLabel6.setText("  Home");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 70));

        panelsidebar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 330, 70));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/search2.png"))); // NOI18N
        jLabel7.setText("  Search Records");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsidebar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 330, 70));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 1040));

        printpanel.setBackground(new java.awt.Color(204, 255, 255));
        printpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Reciept No: SOC - ");
        printpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Mode of Payment :");
        printpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        chequelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chequelbl.setText("Cheque no: ");
        printpanel.add(chequelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        recivedtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recivedtxt.setText(" ");
        printpanel.add(recivedtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("The Following for the year: ");
        printpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("GSIN :");
        printpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        gsintxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gsintxt.setText(" ");
        printpanel.add(gsintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        reciptxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reciptxt.setText(" ");
        printpanel.add(reciptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Date:");
        printpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        datetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datetxt.setText("Date:");
        printpanel.add(datetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText(" -");
        printpanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 30, -1));

        banktxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        banktxt.setText(" ");
        printpanel.add(banktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        year1txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year1txt.setText("Date:");
        printpanel.add(year1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        year2txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year2txt.setText("Date:");
        printpanel.add(year2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        printpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1000, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Sr. No");
        printpanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));
        printpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 1000, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Taxes");
        printpanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Amount (Rs)");
        printpanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        totalinwordstxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalinwordstxt.setText("Total in words");
        printpanel.add(totalinwordstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, -1));

        totalamounttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalamounttxt.setText("Total Amount");
        printpanel.add(totalamounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, -1, -1));

        sgsttt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sgsttt.setText("SGST 9%");
        printpanel.add(sgsttt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Total in words:");
        printpanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 120, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Remarks :");
        printpanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        remarkstxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        remarkstxt.setText("Remarks");
        printpanel.add(remarkstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        amounttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amounttxt.setText("Remarks");
        printpanel.add(amounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, -1, -1));

        cgsttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgsttxt.setText("Remarks");
        printpanel.add(cgsttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, -1, -1));
        printpanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 180, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Recever Signature");
        printpanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 640, 150, 30));

        chequtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chequtxt.setText(" ");
        printpanel.add(chequtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        banklbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        banklbl1.setText("Bank name:");
        printpanel.add(banklbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, -1));

        banklbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        banklbl2.setText("Recieved From:");
        printpanel.add(banklbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        paymentmodetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentmodetxt.setText(" ");
        printpanel.add(paymentmodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        cgsttt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgsttt1.setText("Fees");
        printpanel.add(cgsttt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 70, -1));
        printpanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 180, 20));

        sgsttxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sgsttxt1.setText("Remarks");
        printpanel.add(sgsttxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setText("INSTITUTE MANAGEMENT SYSTEM");
        printpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 910, 100));
        printpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 1000, 10));

        cgsttt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgsttt2.setText("CGST 9%");
        printpanel.add(cgsttt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        getContentPane().add(printpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 1120, 860));

        setBounds(0, 0, 2037, 975);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, intiger }");

//        try {
//
//            printpanel.print(JTable.PrintMode.NORMAL, header, footer);
//        } catch (java.awt.print.PrinterException exx) {
//            System.err.format("No Printer found", exx.getMessage());
//
//        }
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable((Graphics pg, PageFormat pf, int pageNum) -> {
            pf.setOrientation(PageFormat.LANDSCAPE);
            if (pageNum > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.47, 0.47);

            printpanel.print(g2);

            return Printable.PAGE_EXISTS;
        }//            @Override
        //            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        //                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        //            }
        );
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        updatefeesDetails fee = new updatefeesDetails();
        fee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        Addfee_page addfes = new Addfee_page();
        addfes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        viewRecordsall_page viewrecods = new viewRecordsall_page();
        viewrecods.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        Add_Courses_page editcourse = new Add_Courses_page();
        editcourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        home_pageAdmin home = new home_pageAdmin();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        searchrecords_page srch = new searchrecords_page();
        srch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printReciept_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printReciept_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printReciept_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printReciept_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printReciept_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amounttxt;
    private javax.swing.JLabel banklbl1;
    private javax.swing.JLabel banklbl2;
    private javax.swing.JLabel banktxt;
    private javax.swing.JLabel cgsttt1;
    private javax.swing.JLabel cgsttt2;
    private javax.swing.JLabel cgsttxt;
    private javax.swing.JLabel chequelbl;
    private javax.swing.JLabel chequtxt;
    private javax.swing.JLabel datetxt;
    private javax.swing.JLabel gsintxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JLabel paymentmodetxt;
    private javax.swing.JPanel printpanel;
    private javax.swing.JLabel reciptxt;
    private javax.swing.JLabel recivedtxt;
    private javax.swing.JLabel remarkstxt;
    private javax.swing.JLabel sgsttt;
    private javax.swing.JLabel sgsttxt1;
    private javax.swing.JLabel totalamounttxt;
    private javax.swing.JLabel totalinwordstxt;
    private javax.swing.JLabel year1txt;
    private javax.swing.JLabel year2txt;
    // End of variables declaration//GEN-END:variables
}
