package school_management;

import java.sql.Connection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class Report_page extends javax.swing.JFrame {

    DefaultTableModel model;
    Connection Sqlconnection = Connect.ConnectDB();
    PreparedStatement prepared_statement = null;
    ResultSet Result_set = null;

    public Report_page() {
        initComponents();
        coursecombobox();
    }

    public void cleartable() {
//        JOptionPane.showMessageDialog(null, "clear tabel");
        DefaultTableModel RecordTable = (DefaultTableModel) feesdetailstble.getModel();
        RecordTable.setRowCount(0);
    }

    public void setRecordstoTable() {
        String cname = coursecombo.getSelectedItem().toString();
//        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
//        String fromdata = dateformat.format(fromdate.getDate());
//        String todata = dateformat.format(todate.getDate());
        float amounttoatal = 0;
        String courname = "";

        try {
//            prepared_statement = Sqlconnection.prepareStatement("select * from fees_data where date between ? and ? and coursename =?");
            prepared_statement = Sqlconnection.prepareStatement("select * from fees_data where coursename =?");

//            prepared_statement = Sqlconnection.prepareStatement("select * from fees_data where coursename = ?");
//            prepared_statement.setString(1, fromdata);
//            prepared_statement.setString(2, todata);
            prepared_statement.setString(1, cname);

            Result_set = prepared_statement.executeQuery();

            while (Result_set.next()) {
                String recieptno = Result_set.getString("recieptno");
                String rollno = Result_set.getString("registeration");
                String studentname = Result_set.getString("studentname");
                String coursename = Result_set.getString("coursename");
                String paymentmode = Result_set.getString("paymentm");
                String remarks = Result_set.getString("remarks");
                float amount = Result_set.getFloat("amount");
                String date = Result_set.getString("date");

                amounttoatal = amounttoatal + amount;
                courname = coursename;
                Object obj[] = {recieptno, rollno, studentname, coursename, amount, paymentmode, remarks};
                model = (DefaultTableModel) feesdetailstble.getModel();
                model.addRow(obj);
            }

            String s = String.valueOf(amounttoatal);
            courseselected.setText(courname);
            totalamountshow1.setText(s);
            amountwords.setText(NumberToWordsConverter.convert((int) amounttoatal));
        } catch (SQLException ex) {
        }
    }

    private void coursecombobox() {
        try {
            prepared_statement = Sqlconnection.prepareStatement("select course_name from courses");
            Result_set = prepared_statement.executeQuery();

            while (Result_set.next()) {
                coursecombo.addItem(Result_set.getString("course_name"));
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panelsidebar = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        amountwords = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        totalamountshow1 = new javax.swing.JLabel();
        courseselected = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feesdetailstble = new javax.swing.JTable();
        printbtn = new javax.swing.JButton();
        coursecombo = new javax.swing.JComboBox<>();
        printbtn1 = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        Export_excel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/left-arrow.png"))); // NOI18N
        jLabel7.setText("  Back");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 70));

        panelsidebar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 330, 70));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/logout.png"))); // NOI18N
        jLabel1.setText("  Logout");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelsidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 330, 70));

        jPanel16.setBackground(new java.awt.Color(0, 102, 102));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/list_1.png"))); // NOI18N
        jLabel32.setText("  Course List");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsidebar.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 330, 70));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/edit2.png"))); // NOI18N
        jLabel34.setText("  Edit Courses");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsidebar.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 330, 70));

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/search2.png"))); // NOI18N
        jLabel17.setText("  Search Records");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsidebar.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 330, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/home.png"))); // NOI18N
        jLabel6.setText("  Home");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 70));

        panelsidebar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 330, 70));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/view all record.png"))); // NOI18N
        jLabel23.setText("  Report");
        panelsidebar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, 70));
        panelsidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 260, 20));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 820));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Select Course:");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amountwords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel9.add(amountwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 210, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Total Amount in words:");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Total Amount Collected:");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Course Selected:");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        totalamountshow1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalamountshow1.setText(" ");
        jPanel9.add(totalamountshow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 190, 30));

        courseselected.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel9.add(courseselected, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 20, 250, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 430, 170));

        feesdetailstble.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        feesdetailstble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reciept no", "Roll no", "Strudent name", "Course", "Amount", "Remarks"
            }
        ));
        jScrollPane1.setViewportView(feesdetailstble);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 840, 490));

        printbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        jPanel8.add(printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 30));

        coursecombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coursecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        coursecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coursecomboItemStateChanged(evt);
            }
        });
        coursecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursecomboActionPerformed(evt);
            }
        });
        jPanel8.add(coursecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 270, 30));

        printbtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printbtn1.setText("Browse");
        printbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtn1ActionPerformed(evt);
            }
        });
        jPanel8.add(printbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 30));

        searchtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });
        jPanel8.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 270, -1));

        Export_excel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Export_excel.setText("Export to Excel");
        Export_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export_excelActionPerformed(evt);
            }
        });
        jPanel8.add(Export_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 270, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 1560, 820));

        setBounds(0, 0, 2037, 828);
    }// </editor-fold>//GEN-END:initComponents

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, intiger }");

//        try {
//
//            printpanel.print(JTable.PrintMode.NORMAL, header, footer);
//        } catch (java.awt.print.PrinterException exx) {
//            System.err.format("No Printer found", exx.getMessage());
//
//        }
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                feesdetailstble.print(g2);

                return Printable.PAGE_EXISTS;

            }

//            @Override
//            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_printbtnActionPerformed

    private void coursecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursecomboActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        login_page lg = new login_page();
        lg.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        Add_Courses_page editcourse = new Add_Courses_page();
        editcourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        searchrecords_page srch = new searchrecords_page();
        srch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        home_pageAdmin home = new home_pageAdmin();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void printbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printbtn1ActionPerformed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        // TODO add your handling code here:
        String word = searchtxt.getText();
        //        search(word);
    }//GEN-LAST:event_searchtxtKeyReleased

    private void Export_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export_excelActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_Export_excelActionPerformed

    private void coursecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coursecomboItemStateChanged
        // TODO add your handling code here:
        cleartable();
        setRecordstoTable();
    }//GEN-LAST:event_coursecomboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Export_excel;
    private javax.swing.JLabel amountwords;
    private javax.swing.JComboBox<String> coursecombo;
    private javax.swing.JLabel courseselected;
    private javax.swing.JTable feesdetailstble;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton printbtn1;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JLabel totalamountshow1;
    // End of variables declaration//GEN-END:variables
}
