package school_management;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author asgha
 */
public class signup_page extends javax.swing.JFrame {

    Connection Sqlconnection = Connect.ConnectDB();
    PreparedStatement prepared_statement = null;
    ResultSet result_set = null;
//    int q, i, id, deletItem;

//    public void updateDB() {
//        try {
    //            prepared_statement = Sqlconnection.prepareStatement("select * from signupdataadmin");
//
//            result_set = prepared_statement.executeQuery();
//            ResultSetMetaData stData = result_set.getMetaData();
//
//            q = stData.getColumnCount();
////            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
//
//            while (result_set.next()) {
//                Vector columnData = new Vector();
//                for (i = 1; i <= q; i++) {
////                    columnData.add(result_set.getShort("id"));
//                    columnData.add(result_set.getShort("firstname"));
//                    columnData.add(result_set.getShort("lastname"));
//                    columnData.add(result_set.getShort("username"));
//                    columnData.add(result_set.getShort("password"));
//                    columnData.add(result_set.getShort("email"));
//                    columnData.add(result_set.getShort("contact"));
//                }
////                RecordTable.addRow(columnData);               
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    /**
     * Creates new form signup_page
     */
    public signup_page() {
        initComponents();
    }

    String ftname, ltname, usrname, npassword, conpassword, contactnum, emailtx;

    boolean validation() {
        ftname = fnametxt.getText();
        ltname = emailtxt.getText();
        usrname = unametxt.getText();
        npassword = passwordtxt.getText();
        conpassword = confpasswordtxt1.getText();
        contactnum = contacttxt.getText();
        emailtx = emailtxt.getText();

        if (ftname.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter First Name");
            return false;
        }
        if (ltname.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Last Name");
            return false;
        }
        if (usrname.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter User Name");
            return false;
        }
        if (npassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Password");
            return false;
        }
        if (conpassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Confirm Password");
            return false;
        }
        if (emailtx.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter email address");
            return false;
        }

//        if (npassword.length()<8){
//            passerror.setText("Password should be 8 digit");
//         return false;
//        }
        if (!npassword.equals(conpassword)) {
            JOptionPane.showMessageDialog(this, "Password not Matched!");
            return false;

        }
        return true;
    }

//     void checkpassword(){
//        npassword = passwordtxt.getText();
//        
//        if (npassword.length()<8){
//            passerror.setText("Password should be 8 digit");
//         }
//        else{
//            passerror.setText("");            
//        }
//    }
    void checkcontact() {
        contactnum = contacttxt.getText();

        if (contactnum.length() < 11) {
            contacterror.setText("Number should be 11 digit");
        } else {
            contacterror.setText("");
        }
    }

//    boolean insertdetails(){
//        try { 
//            
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql//localhost:3306/schoolmanagement?useSSL=false");
//            
//        } catch (Exception e) {
//        }
//        
//        return true;
//    }
//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lname = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        passwd = new javax.swing.JLabel();
        cpasswd = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        unametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        contacttxt = new javax.swing.JTextField();
        contacterror = new javax.swing.JLabel();
        singinbtn = new javax.swing.JButton();
        signupbtn = new javax.swing.JButton();
        confpasswordtxt1 = new javax.swing.JPasswordField();
        lnametxt1 = new javax.swing.JTextField();
        fname1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/signup.png"))); // NOI18N
        jLabel1.setText("  Signup");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 205, 57));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 100));

        jPanel2.setBackground(new java.awt.Color(0, 152, 150));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("Last Name :");
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 30));

        uname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText("User Name:");
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 30));

        passwd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        passwd.setForeground(new java.awt.Color(255, 255, 255));
        passwd.setText("Password :");
        jPanel2.add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, 30));

        cpasswd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cpasswd.setForeground(new java.awt.Color(255, 255, 255));
        cpasswd.setText("Re Password:");
        jPanel2.add(cpasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        dob.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("Email:");
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, 30));

        contact.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("Contact no:");
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 30));

        fnametxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 320, 30));

        emailtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 320, 30));

        unametxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        unametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unametxtActionPerformed(evt);
            }
        });
        jPanel2.add(unametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 320, 30));

        passwordtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        passwordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordtxtKeyReleased(evt);
            }
        });
        jPanel2.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 320, 30));

        contacttxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });
        contacttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contacttxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contacttxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contacttxtKeyTyped(evt);
            }
        });
        jPanel2.add(contacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 320, 30));

        contacterror.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contacterror.setForeground(new java.awt.Color(255, 0, 0));
        contacterror.setText(" ");
        jPanel2.add(contacterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 285, 47, -1));

        singinbtn.setBackground(new java.awt.Color(0, 51, 102));
        singinbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        singinbtn.setForeground(new java.awt.Color(0, 51, 51));
        singinbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/login.png"))); // NOI18N
        singinbtn.setText("Signin");
        singinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singinbtnActionPerformed(evt);
            }
        });
        jPanel2.add(singinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 180, 40));

        signupbtn.setBackground(new java.awt.Color(0, 51, 102));
        signupbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(0, 51, 51));
        signupbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImages/signup.png"))); // NOI18N
        signupbtn.setText("Singup");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel2.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 358, 180, 40));

        confpasswordtxt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(confpasswordtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 320, 30));

        lnametxt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lnametxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametxt1ActionPerformed(evt);
            }
        });
        jPanel2.add(lnametxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 320, 30));

        fname1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fname1.setForeground(new java.awt.Color(255, 255, 255));
        fname1.setText("First Name :");
        jPanel2.add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 30));

        backButton.setBackground(new java.awt.Color(0, 51, 102));
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 600, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 460));

        setSize(new java.awt.Dimension(568, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void unametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unametxtActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void passwordtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtxtKeyPressed
        // TODO add your handling code here:
//        checkpassword();
    }//GEN-LAST:event_passwordtxtKeyPressed

    private void passwordtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtxtKeyReleased
        // TODO add your handling code here:
//        checkpassword();
    }//GEN-LAST:event_passwordtxtKeyReleased

    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttxtActionPerformed

    private void contacttxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttxtKeyPressed
        // TODO add your handling code here:
        checkcontact();
    }//GEN-LAST:event_contacttxtKeyPressed

    private void contacttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttxtKeyReleased
        // TODO add your handling code here:
        checkcontact();
    }//GEN-LAST:event_contacttxtKeyReleased

    private void contacttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttxtKeyTyped
        // TODO add your handling code here:
        checkcontact();
    }//GEN-LAST:event_contacttxtKeyTyped

    private void singinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singinbtnActionPerformed
        // TODO add your handling code here:
        login_page signin = new login_page();
        signin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_singinbtnActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        validation();
        try {
            //            String fort = forcombo.getSelectedItem().toString();
            prepared_statement = Sqlconnection.prepareStatement("insert into signup_admin(firstname, lastname, username, password, email,contactno)value(?,?,?,?,?,?)");

//            if (fort.equalsIgnoreCase("Adminstrator")) {
//                prepared_statement = Sqlconnection.prepareStatement("insert into signupdata(firstname, lastname, username, password,email"
//                        + "contactno)value(?,?,?,?,?)");
//            }
//            if (fort.equalsIgnoreCase("Student")) {
//                prepared_statement = Sqlconnection.prepareStatement("insert into studentsigup(firstname, lastname, username, password,email,contactno)value(?,?,?,?,?,?)");
//
//            }
            prepared_statement.setString(1, fnametxt.getText());
            prepared_statement.setString(2, emailtxt.getText());
            prepared_statement.setString(3, unametxt.getText());
            prepared_statement.setString(4, passwordtxt.getText());
            prepared_statement.setString(5, emailtxt.getText());
            prepared_statement.setString(6, contacttxt.getText());
            prepared_statement.executeUpdate();

            JOptionPane.showMessageDialog(this, "Signup Successful");
            login_page lg = new login_page();
            lg.setVisible(true);
            this.dispose();
//            updateDB();
        } catch (SQLException ex) {
            Logger.getLogger(signup_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signupbtnActionPerformed

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void lnametxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametxt1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainMenu2 menu = new MainMenu2();;
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField confpasswordtxt1;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel contacterror;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JLabel cpasswd;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel fname1;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField lnametxt1;
    private javax.swing.JLabel passwd;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton signupbtn;
    private javax.swing.JButton singinbtn;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField unametxt;
    // End of variables declaration//GEN-END:variables
}
